### ISSUE TITLE
Errors using Box-Wilson design with the dataset you provided

### ISSUE THREAD

**Issue by Lolultra** [tirthajyoti/Design-of-experiment-Python#2]
Hey,

i got problems using the box-wilson options, here is the error:

Pressure had more than two levels. Assigning the end point to the high level.
Temperature had more than two levels. Assigning the end point to the high level.
FlowRate had more than two levels. Assigning the end point to the high level.
Time had more than two levels. Assigning the end point to the high level.
Traceback (most recent call last):
  File "C:\Users\j.rinne\Desktop\Promotion\Code + Libraries\Python Libraries\Design-of-experiment-Python-master\Design-of-experiment-Python-master\Main.py", line 41, in <module>
    execute_main()
  File "C:\Users\j.rinne\Desktop\Promotion\Code + Libraries\Python Libraries\Design-of-experiment-Python-master\Design-of-experiment-Python-master\Main.py", line 17, in execute_main
    df, filename = generate_DOE(doe_choice,infile)
  File "C:\Users\j.rinne\Desktop\Promotion\Code + Libraries\Python Libraries\Design-of-experiment-Python-master\Design-of-experiment-Python-master\Generate_DOE.py", line 53, in generate_DOE
    df=build_central_composite(dict_vars,face='ccf')
  File "C:\Users\j.rinne\Desktop\Promotion\Code + Libraries\Python Libraries\Design-of-experiment-Python-master\Design-of-experiment-Python-master\DOE_functions.py", line 328, in build_central_composite
    x = ccdesign(factor_count,center=center,alpha=alpha,face=face)
  File "C:\Users\j.rinne\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyDOE\doe_composite.py", line 147, in ccdesign
    H1 = ff2n(n)
  File "C:\Users\j.rinne\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyDOE\doe_factorial.py", line 115, in ff2n
    return 2*fullfact([2]*n) - 1
  File "C:\Users\j.rinne\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyDOE\doe_factorial.py", line 78, in fullfact
    rng = lvl*range_repeat
TypeError: can't multiply sequence by non-int of type 'numpy.float64'

I use python 3.7, maybe thats the problem?

**Comment by mafar** [comment]
is this library active ?

**Comment by ZJZJZJZJZJZJ-code** [comment]
I have the same issue in Python 3.7 any solution on that I am very new on Python all helps appreciated.

**Comment by tirthajyoti** [comment]
Use my new library **`doepy`** which fixed some of the errors. It is still an Alpha (0.0.1) version release. So, appreciate if you give feedback on it.

`pip install doepy`.

[Read the docs here](https://doepy.readthedocs.io/en/latest/)

Closing this issue here now.
